[build]
  command = "yarn prod"
  publish = "dist"

[context.deploy-preview.environment]
  GTMID = "GTM-XXXXXXX"

[context.branch-deploy.environment]
  GTMID = "GTM-XXXXXXX"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
